version: '3'

services:
  world_of_games:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-docker-hub-username/world-of-games:latest
    ports:
      - "5000:5000"  # Adjust the port mapping as needed
